#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Dec 11 11:58:10 CET 2024
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim pong_tb_behav -key {Behavioral:sim_1:Functional:pong_tb} -tclbatch pong_tb.tcl -view /home/filip/src/dsd-project-ba5/lab07_pong/vivado_project/pong_tb_behav.wcfg -log simulate.log"
xsim pong_tb_behav -key {Behavioral:sim_1:Functional:pong_tb} -tclbatch pong_tb.tcl -view /home/filip/src/dsd-project-ba5/lab07_pong/vivado_project/pong_tb_behav.wcfg -log simulate.log

